#!/bin/bash

cc ./a1.0.c -o aq0.out -pthread
cc ./a1.1.c -o aq1.out -pthread
cc ./a1.2.c -o aq2.out -pthread
cc ./a1.3.c -o aq3.out -pthread
cc ./a1.4.c -o aq4.out -pthread
cc ./a1.5.c -o aq5.out -pthread
cc ./a1.6.c -o aq6.out -pthread



